### ISSUE TITLE
MRI 1.2.1 doesn't work with LibreOffice 5.1

### ISSUE THREAD

**Issue by marklh9** [hanya/MRI#5]
After update of LIbreOffice from 5.0.4 to LibreOffice 5.1, it no longer works.
I've tried several versions of MRI, 1.1.5, 1.2.1, 1.3.1. 

Someone also reported the issue to LibreOffice.
https://bugs.documentfoundation.org/show_bug.cgi?id=97401

**Comment by marklh9** [comment]
Error log in when launched by development build(5.2):

set_ui
Traceback (most recent call last):
  File "/home/mark/lo/instdir/user/uno_packages/cache/uno_packages/lu24097evppa.tmp_/MRI-1.2.4.oxt/pythonpath/mytools_Mri/ui/__init__.py", line 52, in __init__
    self.config, self.config.grid, self.config.use_tab)
  File "/home/mark/lo/instdir/user/uno_packages/cache/uno_packages/lu24097evppa.tmp_/MRI-1.2.4.oxt/pythonpath/mytools_Mri/ui/frame.py", line 358, in create_frame
    frame.getController().set_ui(self)
AttributeError: set_ui
Exception 'MRIUi' object has no attribute 'pages'
Traceback (most recent call last):
  File "/home/mark/lo/instdir/user/uno_packages/cache/uno_packages/lu24097evppa.tmp_/MRI-1.2.4.oxt/pythonpath/mytools_Mri/component.py", line 64, in _run_mri
    mri = mytools_Mri.MRI(self.ctx, mytools_Mri.ui.MRIUi)
  File "/home/mark/lo/instdir/user/uno_packages/cache/uno_packages/lu24097evppa.tmp_/MRI-1.2.4.oxt/pythonpath/mytools_Mri/__init__.py", line 54, in __init__
    self.ui = ui_class(ctx, self)
  File "/home/mark/lo/instdir/user/uno_packages/cache/uno_packages/lu24097evppa.tmp_/MRI-1.2.4.oxt/pythonpath/mytools_Mri/ui/__init__.py", line 58, in __init__
    self._init_ui()
  File "/home/mark/lo/instdir/user/uno_packages/cache/uno_packages/lu24097evppa.tmp_/MRI-1.2.4.oxt/pythonpath/mytools_Mri/ui/__init__.py", line 63, in _init_ui
    self.pages.set_font(config.font_name, config.char_size)
AttributeError: 'MRIUi' object has no attribute 'pages'

**Comment by marklh9** [comment]
I tried to fix it myself. But I don't know why it changes from 5.0 to 5.1.

[patch.MRI-1.2.4_For_LO_51.txt](https://github.com/hanya/MRI/files/150803/patch.MRI-1.2.4_For_LO_51.txt)

**Comment by hanya** [comment]
I'm sorry. I have not notice issues related to LO 5.1. 
Please use version 1.3.2 or later.
